! -*- ospf -*-
! Cấu hình định tuyến OSPF cho nút Dist2
hostname dist2
password mininet
log file /tmp/frr_dist2.log

router ospf
 ospf router-id 3.3.3.3
 network 192.168.1.4/30 area 0
 network 172.16.20.0/24 area 0
 redistribute connected
