! -*- ospf -*-
! Cấu hình định tuyến OSPF cho nút Dist1
hostname dist1
password mininet
log file /tmp/frr_dist1.log

router ospf
 ospf router-id 2.2.2.2
 network 192.168.1.0/30 area 0
 network 172.16.10.0/24 area 0
 redistribute connected
