! -*- ospf -*-
! Cấu hình định tuyến OSPF cho nút Core
hostname core
password mininet
log file /tmp/frr_core.log

router ospf
 ospf router-id 1.1.1.1
 network 192.168.1.0/30 area 0
 network 192.168.1.4/30 area 0
 network 192.168.1.8/30 area 0
 network 192.168.100.0/30 area 0

! Phân phối Local Routes để các mạng biết đường ra ngoài
 redistribute connected
 default-information originate
