! ================================================
! FRR Config – DIST2 Router (Distribution Layer)
! File: frr_dist2.conf
! VLAN 20: 172.16.20.0/24
! ================================================

frr version 9.0
frr defaults traditional
hostname dist2
log file /tmp/frr-dist2.log
log timestamp precision 3
!
interface dist2-eth1
 ip ospf hello-interval 5
 ip ospf dead-interval 20
!
interface dist2-eth2
 ip ospf passive
!
router ospf
 ospf router-id 10.255.0.3
 !
 ! Link P2P với Core
 network 192.168.1.4/30  area 0
 !
 ! Mạng VLAN 20 kết nối H2 và IP Phone
 network 172.16.20.0/24  area 0
 !
 passive-interface dist2-eth2
 !
 log-adjacency-changes detail
!
line vty
!
